# General settings
listener 1883
protocol mqtt

# Authentication
allow_anonymous false
password_file data/password_file

# Persistence
persistence true
persistence_location data/

# Logging (relative path)
log_dest file log/mosquitto.log
log_dest stdout
